workflows:
  ios-capacitor-workflow:
    name: Galaxy Rush iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      xcode: latest
      node: 22

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web assets
        script: |
          npm run build || echo "No build script found"

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build iOS
        script: |
          cd ios
          xcodebuild \
            -project App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            archive

    artifacts:
      - ios/build/**/*.ipa
      - ios/build/**/*.xcarchive
